# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Facultate/AN 3/SSC/PROIECT/Proiect_Final/Proiect_filtre/Proiect_filtre.srcs/sources_1/ip/fifo64x64/fifo64x64.xci
# IP: The module: 'fifo64x64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Facultate/AN 3/SSC/PROIECT/Proiect_Final/Proiect_filtre/Proiect_filtre.gen/sources_1/ip/fifo64x64/fifo64x64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo64x64'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Facultate/AN 3/SSC/PROIECT/Proiect_Final/Proiect_filtre/Proiect_filtre.srcs/sources_1/ip/fifo64x64/fifo64x64.xci
# IP: The module: 'fifo64x64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Facultate/AN 3/SSC/PROIECT/Proiect_Final/Proiect_filtre/Proiect_filtre.gen/sources_1/ip/fifo64x64/fifo64x64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo64x64'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
